name: "Check builds"

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  check-build:
    name: check build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        commands:
          - build_darwin_arm64
          - build_linux_amd64
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: ./go.mod
      - name: build
        env:
          COMMAND: ${{ matrix.commands }}
        run: make "${COMMAND}"